services:
  web1:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./www1:/var/www/html
      - ./nginx1.conf:/etc/nginx/conf.d/default.conf
  web2:
    build: .
    ports:
      - "8082:8082"
    volumes:
      - ./www2:/var/www/html
      - ./nginx2.conf:/etc/nginx/conf.d/default.conf
  